[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "csharp_like_file"
version = "0.0.1"
dependencies = [
]

[tool.setuptools.packages.find]
include = ["csfile"]
